import { faker } from "@faker-js/faker";
import { times } from "./array.ts";

export const fakeSurvey = (seed: number) => {
  faker.seed(seed);
  return {
    id: faker.string.uuid(),
    sourceId: faker.string.uuid(),
    year: faker.number.int({ min: 2000, max: 2024 }),
    sampleSize: faker.number.int({ min: 100, max: 10000 }),
    longWording: faker.lorem.sentence(),
    shortWording: faker.lorem.words(5),
    shortObjectives: faker.lorem.sentences(2),
    longObjectives: faker.lorem.paragraph(),
    visaNumber: faker.string.alpha({ length: 8 }), // Assuming 8-character visa numbers
    cnisUrl: faker.internet.url(),
    diffusionUrl: faker.internet.url(),
    noticeUrl: faker.internet.url(),
    specimenUrl: faker.internet.url(),
    communication: faker.lorem.paragraph(),
  };
};

export function fakeCampaignPartitioning(seed: number) {
  faker.seed(seed);
  return {
    id: faker.string.uuid(),
    surveyId: faker.string.uuid(),
    year: faker.number.int({ min: 2023, max: 2050 }),
    campaignWording: faker.lorem.sentence(),
    period: faker.helpers.arrayElement([
      "A00",
      "X00",
      "X01",
      "X02",
      "X03",
      "X04",
      "X05",
      "X06",
      "X07",
      "X08",
      "X09",
      "X10",
      "X11",
      "X12",
      "X13",
      "X14",
      "X15",
      "X16",
      "X17",
      "X18",
      "X19",
      "X20",
      "X21",
      "X22",
      "X23",
      "X24",
      "X25",
      "X26",
      "X27",
      "X28",
      "X29",
      "X30",
      "X31",
      "X32",
      "X33",
      "X34",
      "X35",
      "X36",
      "X37",
      "X38",
      "X39",
      "X40",
      "X41",
      "X42",
      "X43",
      "X44",
      "X45",
      "X46",
      "X47",
      "X48",
      "X49",
      "X50",
      "X51",
      "X52",
      "X53",
      "X54",
      "X55",
      "X56",
      "X57",
      "X58",
      "X59",
      "X60",
      "X61",
      "X62",
      "X63",
      "X64",
      "X65",
      "X66",
      "X67",
      "X68",
      "X69",
      "X70",
      "X71",
      "X72",
      "X73",
      "X74",
      "X75",
      "X76",
      "X77",
      "X78",
      "X79",
      "X80",
      "X81",
      "X82",
      "X83",
      "X84",
      "X85",
      "X86",
      "X87",
      "X88",
      "X89",
      "X90",
      "X91",
      "X92",
      "X93",
      "X94",
      "X95",
      "X96",
      "X97",
      "X98",
      "X99",
      "S01",
      "S02",
      "T01",
      "T02",
      "T03",
      "T04",
      "M01",
      "M02",
      "M03",
      "M04",
      "M05",
      "M06",
      "M07",
      "M08",
      "M09",
      "M10",
      "M11",
      "M12",
      "B01",
      "B02",
      "B03",
      "B04",
      "B05",
      "B06",
    ]),
    partitionings: times(10, fakePartitioning),
  };
}

function fakePartitioning(seed: number) {
  faker.seed(seed);
  return {
    id: faker.string.uuid(),
    campaignId: faker.string.uuid(),
    label: faker.lorem.sentence(),
    openingDate: faker.date.between({
      from: new Date("2024-02-01"),
      to: new Date("2024-02-28"),
    }),
    closingDate: faker.date.between({
      from: new Date("2024-02-01"),
      to: new Date("2024-02-28"),
    }),
    returnDate: faker.date.between({
      from: new Date("2024-02-01"),
      to: new Date("2024-02-28"),
    }),
  };
}
